name: Despliegue Okteto

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - run: okteto deploy --wait
